OPENAI_API_KEY = "<open_api_key>"

[connections.snowpark]
account = '<account>'
user = '<user>'
password = '<password>'
database = '<database>'
schema = '<schema>'
warehouse = '<warehouse>'
role = '<role>'